services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: devtime
      POSTGRES_USER: devtime
      POSTGRES_PASSWORD: devtime
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db/schema/postgres.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
